"use client";

import { useEffect, useState } from "react";
const SITES_ORIGIN = "https://ib-subject-diagnostic.justinamwoo.chatgpt.site";
const moderationFetch = (path: string, init: RequestInit = {}) => { const token = typeof window !== "undefined" ? localStorage.getItem("ibsd-session-token") : null; const headers = new Headers(init.headers); if (token) headers.set("authorization", `Bearer ${token}`); const remote = typeof window !== "undefined" && window.location.hostname.endsWith("github.io"); return fetch(`${remote ? SITES_ORIGIN : ""}${path}`, { ...init, headers }); };
type Case = { id: number; source: string; targetType: string; targetId: number; targetAuthor: string; reason: string; severity: string; signals: Array<{ label: string }>; status: string; createdAt: string; target: null | { title: string | null; body: string; status: string }; reports: Array<{ id: number; reason: string; detail: string; reporterEmail: string }> };
type Sanction = { username: string; accountStatus: string; suspendedUntil: string | null; suspensionReason: string; moderationStrikes: number };
export default function CommunityAdmin() {
  const [cases, setCases] = useState<Case[]>([]); const [sanctions, setSanctions] = useState<Sanction[]>([]); const [stats, setStats] = useState({ visiblePosts: 0, pendingCases: 0, pendingReports: 0 }); const [notes, setNotes] = useState<Record<number, string>>({}); const [busy, setBusy] = useState<string | null>(null); const [message, setMessage] = useState("");
  const load = async () => { const response = await moderationFetch("/api/admin/community", { cache: "no-store" }); const data = await response.json() as { cases?: Case[]; sanctionedAccounts?: Sanction[]; stats?: typeof stats; error?: string }; if (!response.ok) { setMessage(data.error ?? "Moderation data unavailable."); return; } setCases(data.cases ?? []); setSanctions(data.sanctionedAccounts ?? []); setStats(data.stats ?? stats); };
  useEffect(() => { let active = true; moderationFetch("/api/admin/community", { cache: "no-store" }).then((response) => response.json().then((data) => ({ response, data: data as { cases?: Case[]; sanctionedAccounts?: Sanction[]; stats?: typeof stats; error?: string } }))).then(({ response, data }) => { if (!active) return; if (!response.ok) { setMessage(data.error ?? "Moderation data unavailable."); return; } setCases(data.cases ?? []); setSanctions(data.sanctionedAccounts ?? []); setStats(data.stats ?? { visiblePosts: 0, pendingCases: 0, pendingReports: 0 }); }).catch(() => { if (active) setMessage("Moderation data unavailable."); }); return () => { active = false; }; }, []);
  const act = async (caseId: number, action: string) => { setBusy(`${caseId}-${action}`); setMessage(""); const response = await moderationFetch("/api/admin/community", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ caseId, action, adminNote: notes[caseId] ?? "" }) }); const data = await response.json() as { error?: string }; if (!response.ok) setMessage(data.error ?? "Moderation action failed."); else { setMessage("Moderation action saved."); await load(); } setBusy(null); };
  const reinstate = async (targetUser: string) => { setBusy(targetUser); const response = await moderationFetch("/api/admin/community", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "reinstate", targetUser }) }); if (response.ok) { setMessage(`${targetUser} was reinstated.`); await load(); } else setMessage("Account could not be reinstated."); setBusy(null); };
  const pending = cases.filter((item) => item.status === "pending");
  return <section className="community-admin"><div className="section-heading compact"><div><span className="step-label">COMMUNITY</span><h2>Safety review & account sanctions</h2></div><button className="quiet-button" onClick={() => void load()}>Refresh queue</button></div><p className="admin-section-copy">Automated signals and member reports create review cases. Read the content and context before taking account action.</p><div className="moderation-stats"><article><strong>{stats.pendingCases}</strong><span>Pending cases</span></article><article><strong>{stats.pendingReports}</strong><span>Member reports</span></article><article><strong>{stats.visiblePosts}</strong><span>Visible posts</span></article><article><strong>{sanctions.length}</strong><span>Restricted accounts</span></article></div>{message && <div className="premium-message">{message}</div>}
    <div className="moderation-queue">{pending.length ? pending.map((item) => <article className={`moderation-card ${item.severity}`} key={item.id}><header><div><span>{item.source === "automated" ? "AUTOMATED SIGNAL" : "MEMBER REPORT"}</span><h3>{item.targetType} by @{item.targetAuthor}</h3></div><b>{item.severity} priority</b></header><div className="moderation-content">{item.target?.title && <strong>{item.target.title}</strong>}<p>{item.target?.body ?? "Content is no longer available."}</p></div><div className="moderation-signals"><strong>Reason</strong><span>{item.reason}</span>{item.signals.map((signal, index) => <em key={`${signal.label}-${index}`}>{signal.label}</em>)}{item.reports.map((report) => <p key={report.id}><b>{report.reason}</b>{report.detail ? ` · ${report.detail}` : ""} <small>reported by {report.reporterEmail}</small></p>)}</div><label><span>Administrator note</span><textarea value={notes[item.id] ?? ""} onChange={(event) => setNotes((current) => ({ ...current, [item.id]: event.target.value }))} placeholder="Required for removal or account sanctions" maxLength={500}/></label><div className="moderation-actions"><button disabled={Boolean(busy)} onClick={() => void act(item.id, "dismiss")}>Dismiss</button><button disabled={Boolean(busy)} onClick={() => void act(item.id, "remove")}>Remove content</button><button disabled={Boolean(busy)} onClick={() => void act(item.id, "warn")}>Warn</button><button disabled={Boolean(busy)} onClick={() => void act(item.id, "suspend-1d")}>Suspend 1 day</button><button disabled={Boolean(busy)} onClick={() => void act(item.id, "suspend-7d")}>7 days</button><button disabled={Boolean(busy)} onClick={() => void act(item.id, "suspend-30d")}>30 days</button><button className="danger" disabled={Boolean(busy)} onClick={() => void act(item.id, "ban")}>Permanent ban</button></div></article>) : <div className="admin-empty">No community safety cases are waiting for review.</div>}</div>
    <div className="sanction-list"><h3>Restricted accounts</h3>{sanctions.length ? sanctions.map((account) => <article key={account.username}><div><strong>@{account.username}</strong><span>{account.accountStatus}{account.suspendedUntil ? ` until ${new Date(account.suspendedUntil).toLocaleString("en-GB")}` : ""} · {account.moderationStrikes} strike(s)</span><small>{account.suspensionReason}</small></div><button disabled={busy === account.username} onClick={() => void reinstate(account.username)}>Reinstate</button></article>) : <p>No restricted accounts.</p>}</div>
  </section>;
}
