"use client";

import { type FormEvent, useEffect, useMemo, useState } from "react";

const SITES_ORIGIN = "https://ib-subject-diagnostic.justinamwoo.chatgpt.site";
const communityFetch = (path: string, init: RequestInit = {}) => { const token = typeof window !== "undefined" ? localStorage.getItem("ibsd-session-token") : null; const headers = new Headers(init.headers); if (token) headers.set("authorization", `Bearer ${token}`); const remote = typeof window !== "undefined" && window.location.hostname.endsWith("github.io"); return fetch(`${remote ? SITES_ORIGIN : ""}${path}`, { ...init, headers }); };
type Author = { username: string; displayName: string; bio: string; school: string; graduationYear: number | null; avatarColor: string; selectedSubjects: string[] };
type Post = { id: number; title: string; body: string; category: string; tags: string[]; status: string; moderationState: string; pinned: boolean; locked: boolean; viewCount: number; createdAt: string; author: Author; own: boolean; liked: boolean; bookmarked: boolean; followed: boolean; likeCount: number; commentCount: number };
type Comment = { id: number; postId: number; parentId: number | null; body: string; createdAt: string; own: boolean; liked: boolean; likeCount: number; author: Pick<Author, "username" | "displayName" | "avatarColor"> };
type Notification = { id: number; message: string; read: boolean; postId: number | null; createdAt: string };
type CommunityProfile = Author & { postCount: number; followerCount: number; followingCount: number; followed: boolean; own: boolean };
const categoryLabels: Record<string, string> = { "ib-study": "IB study", subjects: "Subjects", "school-life": "School life", university: "University", resources: "Resources", "off-topic": "Off-topic" };
const timeAgo = (value: string) => { const seconds = Math.max(1, Math.floor((Date.now() - new Date(value).getTime()) / 1000)); if (seconds < 60) return `${seconds}s`; if (seconds < 3600) return `${Math.floor(seconds / 60)}m`; if (seconds < 86400) return `${Math.floor(seconds / 3600)}h`; return `${Math.floor(seconds / 86400)}d`; };

export default function CommunityClient({ username, isAdmin, onBack }: { username: string; isAdmin: boolean; onBack: () => void }) {
  const [posts, setPosts] = useState<Post[]>([]); const [categories, setCategories] = useState<Array<{ id: string; label: string }>>([]); const [trending, setTrending] = useState<Array<{ tag: string; count: number }>>([]);
  const [category, setCategory] = useState("all"); const [filter, setFilter] = useState("feed"); const [sort, setSort] = useState("latest"); const [query, setQuery] = useState(""); const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true); const [message, setMessage] = useState(""); const [composer, setComposer] = useState(false); const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [postCategory, setPostCategory] = useState("ib-study"); const [tags, setTags] = useState("");
  const [openPost, setOpenPost] = useState<number | null>(null); const [comments, setComments] = useState<Comment[]>([]); const [commentBody, setCommentBody] = useState(""); const [replyTo, setReplyTo] = useState<Comment | null>(null);
  const [panel, setPanel] = useState<"none" | "notifications" | "profile">("none"); const [notifications, setNotifications] = useState<Notification[]>([]); const [unread, setUnread] = useState(0); const [profile, setProfile] = useState<CommunityProfile | null>(null);
  const [reporting, setReporting] = useState<{ type: "post" | "comment"; id: number } | null>(null); const [reportReason, setReportReason] = useState("harassment"); const [reportDetail, setReportDetail] = useState("");

  const loadPosts = async () => { setLoading(true); const params = new URLSearchParams({ category, filter, sort }); if (search) params.set("q", search); try { const response = await communityFetch(`/api/community/posts?${params}`, { cache: "no-store" }); const data = await response.json() as { posts?: Post[]; categories?: Array<{ id: string; label: string }>; trendingTags?: Array<{ tag: string; count: number }>; unread?: number; error?: string }; if (!response.ok) throw new Error(data.error ?? "Community could not be loaded."); setPosts(data.posts ?? []); setCategories(data.categories ?? []); setTrending(data.trendingTags ?? []); setUnread(data.unread ?? 0); } catch (error) { setMessage(error instanceof Error ? error.message : "Community could not be loaded."); } finally { setLoading(false); } };
  useEffect(() => { let active = true; const params = new URLSearchParams({ category, filter, sort }); if (search) params.set("q", search); communityFetch(`/api/community/posts?${params}`, { cache: "no-store" }).then((response) => response.json().then((data) => ({ response, data: data as { posts?: Post[]; categories?: Array<{ id: string; label: string }>; trendingTags?: Array<{ tag: string; count: number }>; unread?: number; error?: string } }))).then(({ response, data }) => { if (!active) return; if (!response.ok) throw new Error(data.error ?? "Community could not be loaded."); setPosts(data.posts ?? []); setCategories(data.categories ?? []); setTrending(data.trendingTags ?? []); setUnread(data.unread ?? 0); setLoading(false); }).catch((error) => { if (active) { setMessage(error instanceof Error ? error.message : "Community could not be loaded."); setLoading(false); } }); return () => { active = false; }; }, [category, filter, sort, search]);
  const apiAction = async (path: string, payload: Record<string, unknown>) => { setMessage(""); const response = await communityFetch(path, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error ?? "The action could not be completed."); return data; };
  const createPost = async (event: FormEvent) => { event.preventDefault(); try { const response = await communityFetch("/api/community/posts", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ title, body, category: postCategory, tags }) }); const data = await response.json() as { error?: string; moderation?: { hidden?: boolean } }; if (!response.ok) throw new Error(data.error ?? "Post could not be published."); setTitle(""); setBody(""); setTags(""); setComposer(false); setMessage(data.moderation?.hidden ? "Your post is hidden while the administrator reviews a safety signal." : "Post published."); await loadPosts(); } catch (error) { setMessage(error instanceof Error ? error.message : "Post could not be published."); } };
  const togglePost = async (post: Post, action: "like" | "bookmark" | "follow" | "pin" | "lock") => { try { await apiAction("/api/community/posts", { action, postId: post.id, targetUser: post.author.username }); await loadPosts(); } catch (error) { setMessage(error instanceof Error ? error.message : "Action failed."); } };
  const editPost = async (post: Post) => { const nextTitle = window.prompt("Edit title", post.title); if (nextTitle === null) return; const nextBody = window.prompt("Edit post", post.body); if (nextBody === null) return; try { await apiAction("/api/community/posts", { action: "edit", postId: post.id, title: nextTitle, body: nextBody, category: post.category, tags: post.tags }); await loadPosts(); } catch (error) { setMessage(error instanceof Error ? error.message : "Post could not be edited."); } };
  const deletePost = async (post: Post) => { if (!window.confirm("Delete this post?")) return; try { await apiAction("/api/community/posts", { action: "delete", postId: post.id }); setOpenPost(null); await loadPosts(); } catch (error) { setMessage(error instanceof Error ? error.message : "Post could not be deleted."); } };
  const openComments = async (post: Post) => { setOpenPost(openPost === post.id ? null : post.id); if (openPost === post.id) return; void apiAction("/api/community/posts", { action: "view", postId: post.id }).catch(() => undefined); const response = await communityFetch(`/api/community/comments?postId=${post.id}`, { cache: "no-store" }); const data = await response.json() as { comments?: Comment[] }; setComments(data.comments ?? []); };
  const addComment = async (event: FormEvent) => { event.preventDefault(); if (!openPost) return; try { const response = await communityFetch("/api/community/comments", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ postId: openPost, parentId: replyTo?.id ?? null, body: commentBody }) }); const data = await response.json() as { error?: string; moderation?: { hidden?: boolean } }; if (!response.ok) throw new Error(data.error ?? "Comment could not be posted."); setCommentBody(""); setReplyTo(null); const refreshed = await communityFetch(`/api/community/comments?postId=${openPost}`, { cache: "no-store" }).then((item) => item.json()) as { comments?: Comment[] }; setComments(refreshed.comments ?? []); setMessage(data.moderation?.hidden ? "Your comment is hidden pending administrator review." : ""); await loadPosts(); } catch (error) { setMessage(error instanceof Error ? error.message : "Comment could not be posted."); } };
  const changeComment = async (comment: Comment, action: "like" | "edit" | "delete") => { const payload: Record<string, unknown> = { action, commentId: comment.id }; if (action === "edit") { const body = window.prompt("Edit comment", comment.body); if (body === null) return; payload.body = body; } if (action === "delete" && !window.confirm("Delete this comment?")) return; try { await apiAction("/api/community/comments", payload); if (openPost) { const data = await communityFetch(`/api/community/comments?postId=${openPost}`, { cache: "no-store" }).then((item) => item.json()) as { comments?: Comment[] }; setComments(data.comments ?? []); } } catch (error) { setMessage(error instanceof Error ? error.message : "Comment action failed."); } };
  const submitReport = async (event: FormEvent) => { event.preventDefault(); if (!reporting) return; try { const response = await communityFetch("/api/community/reports", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ targetType: reporting.type, targetId: reporting.id, reason: reportReason, detail: reportDetail }) }); const data = await response.json() as { error?: string; message?: string }; if (!response.ok) throw new Error(data.error ?? "Report failed."); setMessage(data.message ?? "Report sent."); setReporting(null); setReportDetail(""); } catch (error) { setMessage(error instanceof Error ? error.message : "Report failed."); } };
  const loadNotifications = async () => { const data = await communityFetch("/api/community/notifications", { cache: "no-store" }).then((response) => response.json()) as { notifications?: Notification[] }; setNotifications(data.notifications ?? []); setPanel("notifications"); await apiAction("/api/community/notifications", { all: true }); setUnread(0); };
  const loadProfile = async (target = username) => { const response = await communityFetch(`/api/community/profile?user=${encodeURIComponent(target)}`, { cache: "no-store" }); const data = await response.json() as { profile?: CommunityProfile; error?: string }; if (!response.ok || !data.profile) { setMessage(data.error ?? "Profile unavailable."); return; } setProfile(data.profile); setPanel("profile"); };
  const saveProfile = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!profile) return; const form = new FormData(event.currentTarget); try { await apiAction("/api/community/profile", { bio: form.get("bio"), school: form.get("school"), graduationYear: Number(form.get("graduationYear")) || null, avatarColor: form.get("avatarColor") }); await loadProfile(username); setMessage("Profile saved."); } catch (error) { setMessage(error instanceof Error ? error.message : "Profile could not be saved."); } };
  const selectedPost = useMemo(() => posts.find((post) => post.author.username === profile?.username) ?? null, [posts, profile?.username]);

  return <main className="commons-shell">
    <header className="commons-header"><button className="commons-brand" onClick={() => { setFilter("feed"); setCategory("all"); }}><i>◎</i><span><strong>IB COMMONS</strong><small>Premium community</small></span></button><form className="commons-search" onSubmit={(event) => { event.preventDefault(); setSearch(query.trim()); }}><span>⌕</span><input aria-label="Search discussions" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search discussions, subjects or tags"/><button>Search</button></form><nav><button onClick={() => void loadNotifications()}>Alerts{unread > 0 && <b>{unread}</b>}</button><button onClick={() => void loadProfile(username)}>Profile</button><button className="back-to-study" onClick={onBack}>Subject Diagnostic ↗</button></nav></header>
    <div className="commons-layout"><aside className="commons-left"><button className="new-thread" onClick={() => setComposer(true)}>＋ Start a discussion</button><strong>EXPLORE</strong><button className={filter === "feed" && category === "all" ? "active" : ""} onClick={() => { setFilter("feed"); setCategory("all"); }}>⌂ Community feed</button>{categories.map((item) => <button key={item.id} className={category === item.id ? "active" : ""} onClick={() => { setFilter("feed"); setCategory(item.id); }}>{item.label}</button>)}<strong>YOUR SPACE</strong><button className={filter === "bookmarks" ? "active" : ""} onClick={() => setFilter("bookmarks")}>◇ Bookmarks</button><button className={filter === "mine" ? "active" : ""} onClick={() => setFilter("mine")}>☰ My posts</button>{isAdmin && <button onClick={onBack}>⚙ Admin console</button>}</aside>
      <section className="commons-feed"><div className="commons-welcome"><div><span>PREMIUM MEMBER SPACE</span><h1>Talk, ask, share.</h1><p>IB questions, school life, university plans—or anything respectful.</p></div><button onClick={() => setComposer(true)}>Write a post</button></div><div className="feed-toolbar"><strong>{filter === "bookmarks" ? "Saved discussions" : filter === "mine" ? "Your discussions" : category === "all" ? "Latest discussions" : categoryLabels[category]}</strong><select value={sort} onChange={(event) => setSort(event.target.value)}><option value="latest">Latest</option><option value="popular">Popular</option><option value="unanswered">Unanswered</option></select></div>{message && <div className="commons-message" role="status">{message}<button onClick={() => setMessage("")}>×</button></div>}
        {loading ? <div className="commons-empty">Loading discussions…</div> : posts.length ? posts.map((post) => <article className={`thread-card ${post.pinned ? "pinned" : ""}`} key={post.id}><div className={`commons-avatar ${post.author.avatarColor}`}>{post.author.displayName.slice(0, 1).toUpperCase()}</div><div className="thread-main"><div className="thread-meta"><button onClick={() => void loadProfile(post.author.username)}>{post.author.displayName}</button><span>· {timeAgo(post.createdAt)}</span><em>{categoryLabels[post.category] ?? post.category}</em>{post.pinned && <b>PINNED</b>}{post.locked && <b>LOCKED</b>}{post.own && post.moderationState !== "clean" && <b className="reviewing">UNDER REVIEW</b>}</div><button className="thread-copy" onClick={() => void openComments(post)}><h2>{post.title}</h2><p>{post.body}</p></button><div className="thread-tags">{post.tags.map((tag) => <button key={tag} onClick={() => { setQuery(tag); setSearch(tag); }}>#{tag}</button>)}</div><div className="thread-actions"><button className={post.liked ? "active" : ""} onClick={() => void togglePost(post, "like")}>♡ {post.likeCount}</button><button onClick={() => void openComments(post)}>◯ {post.commentCount}</button><button className={post.bookmarked ? "active" : ""} onClick={() => void togglePost(post, "bookmark")}>◇ {post.bookmarked ? "Saved" : "Save"}</button><button onClick={() => void navigator.clipboard?.writeText(`${location.origin}${location.pathname}#community-post-${post.id}`).then(() => setMessage("Link copied."))}>↗ Share</button>{!post.own && <button onClick={() => setReporting({ type: "post", id: post.id })}>! Report</button>}{post.own && <><button onClick={() => void editPost(post)}>Edit</button><button onClick={() => void deletePost(post)}>Delete</button></>}{!post.own && <button onClick={() => void togglePost(post, "follow")}>{post.followed ? "Following" : "Follow"}</button>}{isAdmin && <><button onClick={() => void togglePost(post, "pin")}>{post.pinned ? "Unpin" : "Pin"}</button><button onClick={() => void togglePost(post, "lock")}>{post.locked ? "Unlock" : "Lock"}</button></>}</div>{openPost === post.id && <CommentThread post={post} comments={comments} body={commentBody} replyTo={replyTo} onBody={setCommentBody} onReply={setReplyTo} onSubmit={addComment} onChange={changeComment} onReport={(id) => setReporting({ type: "comment", id })}/>}</div></article>) : <div className="commons-empty"><strong>No discussions here yet.</strong><p>Start the first respectful conversation.</p><button onClick={() => setComposer(true)}>Create a post</button></div>}
      </section><aside className="commons-right"><section><span>COMMUNITY NOTE</span><h3>Built for honest conversation.</h3><p>Disagree with ideas, not people. Protect everyone&apos;s privacy and report anything unsafe.</p><ul><li>No harassment or threats</li><li>No personal information</li><li>No spam or impersonation</li></ul></section><section><span>TRENDING TAGS</span>{trending.length ? trending.map((item) => <button key={item.tag} onClick={() => { setQuery(item.tag); setSearch(item.tag); }}>#{item.tag}<b>{item.count}</b></button>) : <p>Tags will appear as members post.</p>}</section><section className="moderation-note"><strong>How safety works</strong><p>Automated rules flag risk signals. Reports and context are reviewed by the administrator before account sanctions.</p></section></aside></div>
    {composer && <div className="commons-modal" role="dialog" aria-modal="true"><form onSubmit={createPost}><div className="modal-heading"><div><span>NEW DISCUSSION</span><h2>What do you want to share?</h2></div><button type="button" onClick={() => setComposer(false)}>×</button></div><label><span>Category</span><select value={postCategory} onChange={(event) => setPostCategory(event.target.value)}>{categories.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label><span>Title</span><input value={title} onChange={(event) => setTitle(event.target.value)} maxLength={120} required placeholder="Make the topic easy to understand"/></label><label><span>Post</span><textarea value={body} onChange={(event) => setBody(event.target.value)} maxLength={5000} required placeholder="Add context, what you tried, or what you want others to discuss"/><small>{body.length}/5000</small></label><label><span>Tags</span><input value={tags} onChange={(event) => setTags(event.target.value)} placeholder="economics, paper-1, study-tips"/><small>Up to five, separated by commas</small></label><div className="modal-actions"><button type="button" onClick={() => setComposer(false)}>Cancel</button><button className="publish-thread">Publish discussion</button></div></form></div>}
    {reporting && <div className="commons-modal small" role="dialog" aria-modal="true"><form onSubmit={submitReport}><div className="modal-heading"><div><span>PRIVATE REPORT</span><h2>Tell the administrator</h2></div><button type="button" onClick={() => setReporting(null)}>×</button></div><label><span>Reason</span><select value={reportReason} onChange={(event) => setReportReason(event.target.value)}><option value="harassment">Harassment</option><option value="hate-or-abuse">Hate or abuse</option><option value="threat">Threat or safety risk</option><option value="privacy">Private information</option><option value="sexual-content">Sexual content</option><option value="spam">Spam</option><option value="misinformation">Misinformation</option><option value="other">Other</option></select></label><label><span>Context (optional)</span><textarea value={reportDetail} onChange={(event) => setReportDetail(event.target.value)} maxLength={500}/></label><div className="modal-actions"><button type="button" onClick={() => setReporting(null)}>Cancel</button><button className="publish-thread">Send report</button></div></form></div>}
    {panel !== "none" && <div className="commons-drawer"><button className="drawer-close" onClick={() => setPanel("none")}>×</button>{panel === "notifications" ? <><span className="drawer-label">NOTIFICATIONS</span><h2>Your activity</h2>{notifications.length ? notifications.map((item) => <article key={item.id}><i className={item.read ? "" : "new"}/><div><p>{item.message}</p><small>{timeAgo(item.createdAt)} ago</small></div></article>) : <div className="commons-empty">No notifications yet.</div>}</> : profile && <><span className="drawer-label">MEMBER PROFILE</span><div className={`profile-avatar ${profile.avatarColor}`}>{profile.displayName.slice(0, 1).toUpperCase()}</div><h2>{profile.displayName}</h2><p className="profile-handle">@{profile.username}</p><div className="profile-stats"><span><strong>{profile.postCount}</strong>posts</span><span><strong>{profile.followerCount}</strong>followers</span><span><strong>{profile.followingCount}</strong>following</span></div>{profile.own ? <form className="profile-form" onSubmit={saveProfile}><label><span>Bio</span><textarea name="bio" defaultValue={profile.bio} maxLength={300}/></label><label><span>School (optional)</span><input name="school" defaultValue={profile.school} maxLength={80}/></label><label><span>Graduation year</span><input name="graduationYear" type="number" defaultValue={profile.graduationYear ?? ""}/></label><label><span>Avatar colour</span><select name="avatarColor" defaultValue={profile.avatarColor}>{["indigo", "coral", "teal", "amber", "plum", "sky"].map((color) => <option key={color}>{color}</option>)}</select></label><button className="publish-thread">Save profile</button></form> : <><p className="profile-bio">{profile.bio || "No bio yet."}</p>{profile.school && <p>{profile.school}{profile.graduationYear ? ` · Class of ${profile.graduationYear}` : ""}</p>}<button className="publish-thread" onClick={() => selectedPost && void togglePost(selectedPost, "follow")}>{profile.followed ? "Following" : "Follow member"}</button></>}</>}</div>}
  </main>;
}

function CommentThread({ post, comments, body, replyTo, onBody, onReply, onSubmit, onChange, onReport }: { post: Post; comments: Comment[]; body: string; replyTo: Comment | null; onBody: (value: string) => void; onReply: (comment: Comment | null) => void; onSubmit: (event: FormEvent) => void; onChange: (comment: Comment, action: "like" | "edit" | "delete") => void; onReport: (id: number) => void }) {
  const roots = comments.filter((comment) => !comment.parentId); const replies = (id: number) => comments.filter((comment) => comment.parentId === id);
  const row = (comment: Comment, nested = false) => <div className={`comment-row ${nested ? "reply" : ""}`} key={comment.id}><div className={`commons-avatar small ${comment.author.avatarColor}`}>{comment.author.displayName.slice(0, 1).toUpperCase()}</div><div><div><strong>{comment.author.displayName}</strong><small>{timeAgo(comment.createdAt)}</small></div><p>{comment.body}</p><nav><button onClick={() => void onChange(comment, "like")}>♡ {comment.likeCount}</button>{!nested && <button onClick={() => onReply(comment)}>Reply</button>}{comment.own ? <><button onClick={() => void onChange(comment, "edit")}>Edit</button><button onClick={() => void onChange(comment, "delete")}>Delete</button></> : <button onClick={() => onReport(comment.id)}>Report</button>}</nav></div></div>;
  return <section className="comment-thread"><div className="comment-list">{roots.length ? roots.map((comment) => <div key={comment.id}>{row(comment)}{replies(comment.id).map((reply) => row(reply, true))}</div>) : <p className="first-comment">No replies yet. Add the first one.</p>}</div>{!post.locked && <form onSubmit={onSubmit}>{replyTo && <div className="replying">Replying to {replyTo.author.displayName}<button type="button" onClick={() => onReply(null)}>×</button></div>}<textarea value={body} onChange={(event) => onBody(event.target.value)} placeholder="Add to the discussion…" required maxLength={2000}/><button>Reply</button></form>}</section>;
}
