import type { Level, Paper, Question, Subject, Topic } from "./data";

type Node = Topic & { path: string; profile: string; examples: string[] };

const n = (code: string, title: string, level: "both" | "HL", path: string, definition: string, concepts: string[], application: string, misconception: string, profile: string, examples: string[] = []): Node => ({ code, title, level, path, definition, concepts, application, misconception, profile, examples });

const P = {
  business: "BM_current_case_toolkit",
  economics: "ECON_current_DP",
  geography: "GEO_PPPPSS_current",
  "global-politics": "GP_current_source_essay",
  history: "HIST_authoritarian_rule",
  philosophy: "PHIL_being_human",
  psychology: "PSY_Oxford_2025_new_course",
  anthropology: "SCA_ethnography_profile",
  "digital-society": "DS_current_sociotechnical",
} as const;

export const INS_TOPICS: Record<string, Node[]> = {
  business: [
    n("BM1.1", "What is a business?", "both", "Unit 1 > Introduction > business activity and sectors", "Businesses organize resources to produce goods or services and create value while pursuing objectives.", ["business activity", "added value", "sector", "entrepreneurship"], "distinguish business activity from a charity or public service", "every organization exists only to maximize profit", P.business),
    n("BM1.2", "Business entities", "both", "Unit 1 > Introduction > legal forms and ownership", "Legal form changes ownership, liability, continuity, finance and control.", ["sole trader", "partnership", "private company", "social enterprise"], "recommend a legal form using owners' stated priorities", "limited liability means a business cannot fail", P.business),
    n("BM1.3", "Objectives and strategy", "both", "Unit 1 > Objectives > mission, vision and change", "Objectives guide decisions but may change with internal and external conditions.", ["mission", "vision", "objective", "strategy"], "analyse a conflict between growth and sustainability", "objectives remain fixed throughout a firm's life", P.business),
    n("BM1.4", "Stakeholders", "both", "Unit 1 > Stakeholders > conflict and change", "Stakeholders have distinct interests, influence and exposure to business decisions.", ["stakeholder", "shareholder", "conflict", "power"], "evaluate a decision from employee, owner and community perspectives", "all stakeholders benefit from higher profit", P.business),
    n("BM1.5", "Growth and evolution", "both", "Unit 1 > Growth > internal and external growth", "Growth may create economies of scale but also coordination, culture and finance risks.", ["internal growth", "merger", "economies of scale", "diseconomies"], "evaluate organic growth against acquisition", "larger firms always have lower unit costs", P.business),
    n("BM2.2", "Organizational structure", "both", "Unit 2 > HRM > structure, delegation and span", "Structure allocates authority, accountability and communication across an organization.", ["hierarchy", "delegation", "span of control", "matrix structure"], "recommend a structure for a growing firm", "a flatter structure always improves communication", P.business),
    n("BM2.3", "Leadership and management", "both", "Unit 2 > HRM > leadership styles", "Leadership style affects decision speed, motivation, participation and suitability for context.", ["autocratic", "democratic", "situational leadership", "management"], "analyse which style suits a crisis and a creative team", "democratic leadership is always the most motivating", P.business),
    n("BM2.4", "Motivation", "both", "Unit 2 > HRM > motivation and demotivation", "Motivation depends on financial and non-financial factors and how work is designed.", ["motivation", "Herzberg", "Taylor", "job enrichment"], "evaluate a pay rise against job enrichment", "money is the only effective motivator", P.business),
    n("BM3.4", "Profitability and liquidity", "both", "Unit 3 > Finance > ratio analysis", "Ratios support comparison but require context, trends and limitations.", ["gross profit margin", "net profit margin", "current ratio", "liquidity"], "calculate and interpret changing ratios", "a profitable business cannot face cash-flow problems", P.business),
    n("BM3.7", "Investment appraisal", "both", "Unit 3 > Finance > payback and ARR", "Investment appraisal compares financial returns but cannot fully capture risk or qualitative effects.", ["payback", "average rate of return", "investment", "risk"], "compare two projects using calculations and qualitative evidence", "the shortest payback is automatically the best investment", P.business),
    n("BM4.2", "Marketing planning", "both", "Unit 4 > Marketing > segmentation, targeting and positioning", "Marketing planning aligns objectives, market information, segmentation and the marketing mix.", ["segmentation", "target market", "positioning", "market share"], "recommend a target market using research evidence", "a larger market segment is always more attractive", P.business),
    n("BM4.5", "The seven Ps", "both", "Unit 4 > Marketing > product, price, promotion, place, people, process, physical evidence", "The marketing mix must be coherent and suited to customer needs and competitive conditions.", ["product", "price", "promotion", "place"], "analyse how two Ps interact", "changing promotion alone guarantees sales growth", P.business),
    n("BM5.3", "Lean production and quality", "both", "Unit 5 > Operations > lean production and quality management", "Lean methods reduce waste while quality systems aim for consistent customer requirements.", ["lean production", "quality assurance", "quality control", "kaizen"], "evaluate lean production for a growing manufacturer", "lean production simply means dismissing workers", P.business),
    n("BM5.5", "Break-even analysis", "both", "Unit 5 > Operations > contribution and break-even", "Break-even analysis relates fixed costs, contribution and output but depends on stable assumptions.", ["fixed cost", "variable cost", "contribution", "break-even"], "calculate break-even and assess a price decision", "revenue above fixed cost means profit", P.business),
    n("BM-TK-HL", "HL strategic tools", "HL", "Business toolkit > HL tools > force field, critical path and strategy", "HL tools structure decisions but must be interpreted with their assumptions and limits.", ["force field analysis", "critical path", "Porter strategy", "regression"], "select and apply the most suitable strategic tool", "using a named tool automatically produces a valid recommendation", P.business),
  ],
  economics: [
    n("ECO1.1", "Scarcity and opportunity cost", "both", "Foundations > scarcity > choice and opportunity cost", "Finite resources require choices whose opportunity cost is the next best alternative forgone.", ["scarcity", "choice", "opportunity cost", "factors of production"], "apply opportunity cost to a policy choice", "opportunity cost is the money price paid", P.economics),
    n("ECO1.2", "Production possibility curves", "both", "Foundations > PPC > efficiency, growth and opportunity cost", "A PPC represents maximum combinations under current resources and technology.", ["PPC", "productive efficiency", "unemployment", "economic growth"], "explain movements and shifts on a labelled PPC", "every point inside a PPC is unattainable", P.economics),
    n("ECO2.1", "Demand, supply and equilibrium", "both", "Microeconomics > markets > demand, supply and equilibrium", "Competitive equilibrium coordinates planned demand and supply through price signals.", ["demand", "supply", "equilibrium", "price mechanism"], "analyse simultaneous demand and supply shifts", "a change in price shifts the demand curve", P.economics),
    n("ECO2.2", "Elasticities", "both", "Microeconomics > elasticity > PED, YED, XED and PES", "Elasticities measure responsiveness and depend on time, substitutes, necessity and capacity.", ["PED", "PES", "revenue", "incidence"], "calculate elasticity and interpret business or policy implications", "elastic demand means quantity changes by less than price", P.economics),
    n("ECO2.3", "Indirect taxes", "both", "Microeconomics > intervention > indirect taxation", "An indirect tax creates a wedge, changes equilibrium and distributes burden according to relative elasticities.", ["indirect tax", "tax incidence", "consumer surplus", "welfare loss"], "construct and explain a tax diagram", "producers always pay the full tax", P.economics),
    n("ECO2.4", "Subsidies and price controls", "both", "Microeconomics > intervention > subsidies, ceilings and floors", "Interventions change incentives and may create fiscal costs, shortages, surpluses or welfare effects.", ["subsidy", "price ceiling", "price floor", "government expenditure"], "evaluate intervention using stakeholders and unintended effects", "a binding price ceiling creates a surplus", P.economics),
    n("ECO2.5", "Externalities", "both", "Microeconomics > market failure > externalities and policy", "External costs or benefits create divergence between private and social outcomes.", ["externality", "MSC", "MSB", "social optimum"], "construct a welfare diagram and compare policies", "all pollution is eliminated at the social optimum", P.economics),
    n("ECO2.6", "Public goods and information failure", "both", "Microeconomics > market failure > public goods and asymmetric information", "Non-excludability, non-rivalry and information asymmetry can prevent efficient allocation.", ["public good", "free rider", "asymmetric information", "moral hazard"], "distinguish policy responses to different failures", "a publicly provided service is automatically a public good", P.economics),
    n("ECO3.1", "AD, AS and equilibrium", "both", "Macroeconomics > AD-AS > components, shifts and equilibrium", "Aggregate demand and aggregate supply determine real output and the price level within a model.", ["aggregate demand", "short-run aggregate supply", "long-run aggregate supply", "output gap"], "explain a policy transmission mechanism with AD-AS", "a rise in consumption always increases long-run potential output", P.economics),
    n("ECO3.2", "Inflation and unemployment", "both", "Macroeconomics > objectives > inflation and unemployment", "Inflation and unemployment have multiple causes, costs and measurement limitations.", ["inflation", "unemployment", "CPI", "natural rate"], "evaluate policies for a specified cause", "all unemployment is caused by insufficient demand", P.economics),
    n("ECO3.3", "Monetary and fiscal policy", "both", "Macroeconomics > demand-side policy > monetary and fiscal", "Demand-side policies affect spending through interest rates, taxes and government expenditure, with lags and trade-offs.", ["monetary policy", "fiscal policy", "multiplier", "crowding out"], "evaluate effectiveness by economic conditions", "lower interest rates guarantee higher investment", P.economics),
    n("ECO3.4", "Supply-side policy", "both", "Macroeconomics > supply-side policy > market-based and interventionist", "Supply-side policies aim to expand productive capacity but differ in cost, equity and time horizon.", ["supply-side policy", "productivity", "incentive", "human capital"], "compare interventionist and market-based policies", "supply-side policies have no demand-side effects", P.economics),
    n("ECO4.1", "Trade and protection", "both", "Global economy > trade > comparative advantage and protectionism", "Trade may increase specialization and choice while protection redistributes welfare among stakeholders.", ["comparative advantage", "tariff", "quota", "producer surplus"], "evaluate a tariff with a labelled diagram and evidence", "free trade benefits every stakeholder equally", P.economics),
    n("ECO4.2", "Exchange rates", "both", "Global economy > exchange rates > determination and consequences", "Currency demand and supply determine floating rates; changes affect trade, inflation and stakeholders.", ["appreciation", "depreciation", "exchange rate", "current account"], "analyse exchange-rate change in a specific economy", "depreciation immediately improves the current account", P.economics),
    n("ECO4.3", "Development", "both", "Global economy > development > measurement, barriers and strategies", "Development is multidimensional and shaped by institutions, inequality, resources and policy.", ["economic development", "HDI", "poverty", "sustainability"], "evaluate a development strategy using multiple indicators", "GDP per capita fully measures development", P.economics),
    n("ECO-HL", "HL quantitative integration", "HL", "HL extension > quantitative micro, macro and global analysis", "HL analysis integrates calculations, diagrams and policy reasoning.", ["multiplier", "terms of trade", "welfare", "policy recommendation"], "solve quantitative data then recommend policy", "a correct calculation is sufficient without interpretation", P.economics),
  ],
  geography: [
    n("GEO1.1", "Population and development patterns", "both", "Unit 1 > population > development patterns", "Population indicators vary spatially and relate to development through complex processes.", ["fertility", "mortality", "dependency ratio", "demographic transition"], "interpret a population dataset across places", "population growth alone determines development", P.geography),
    n("GEO1.2", "Migration and place", "both", "Unit 1 > changing populations > migration and place", "Migration connects origins and destinations through push, pull and intervening factors at multiple scales.", ["migration", "push factor", "pull factor", "remittance"], "explain a flow using place-specific evidence", "migration decisions are caused by one factor", P.geography),
    n("GEO1.3", "Population challenges", "both", "Unit 1 > population > challenges and opportunities", "Ageing, youthful populations and demographic dividends create context-dependent opportunities and pressures.", ["ageing", "demographic dividend", "policy", "dependency"], "evaluate a population policy", "a youthful population automatically creates a demographic dividend", P.geography),
    n("GEO2.1", "Climate causes", "both", "Unit 2 > climate > causes and responsibility", "Climate change arises from forcing, feedbacks and uneven contributions across actors and places.", ["greenhouse gas", "forcing", "feedback", "responsibility"], "explain a causal system using evidence", "all countries contribute equally to climate change", P.geography),
    n("GEO2.2", "Vulnerability and impacts", "both", "Unit 2 > climate > vulnerability and consequences", "Risk reflects hazard, exposure, vulnerability and adaptive capacity rather than hazard alone.", ["hazard", "vulnerability", "exposure", "adaptive capacity"], "compare impacts in two places", "a stronger hazard always produces greater losses", P.geography),
    n("GEO2.3", "Mitigation and adaptation", "both", "Unit 2 > climate > responses and resilience", "Mitigation reduces drivers while adaptation reduces harm; effectiveness varies by scale and power.", ["mitigation", "adaptation", "resilience", "governance"], "evaluate a response for a named place", "adaptation directly cuts greenhouse emissions", P.geography),
    n("GEO3.1", "Resource consumption", "both", "Unit 3 > resources > consumption and security", "Resource consumption varies with income, technology, population and values, producing uneven footprints.", ["resource security", "ecological footprint", "consumption", "inequality"], "describe and explain a resource graph", "population size alone explains consumption", P.geography),
    n("GEO3.2", "Water-food-energy nexus", "both", "Unit 3 > resources > water-food-energy nexus", "Decisions in one resource system create trade-offs and feedbacks in others.", ["nexus", "water security", "food security", "energy security"], "analyse an intervention across all three systems", "increasing one supply has no effect on other resources", P.geography),
    n("GEO3.3", "Resource stewardship", "both", "Unit 3 > resources > stewardship", "Stewardship combines efficiency, substitution, governance and behavioral change at different scales.", ["stewardship", "circular economy", "conservation", "scale"], "evaluate a stewardship strategy", "recycling removes the need for primary resources", P.geography),
    n("GEO4", "Power, places and networks", "HL", "Unit 4 HL > power, places and networks", "Global power operates through states, firms, cities, networks and flows that create uneven interdependence.", ["globalization", "network", "flow", "power"], "analyse a global network and its uneven effects", "globalization affects all places uniformly", P.geography),
    n("GEO5", "Human development and diversity", "HL", "Unit 5 HL > development, identity and culture", "Development and cultural change reflect power, resistance, hybridity and place-based possibilities.", ["development", "identity", "cultural diffusion", "resistance"], "compare how places accept or resist change", "cultural change means cultural loss only", P.geography),
    n("GEO6", "Global risks and resilience", "HL", "Unit 6 HL > risks and resilience", "Risks interact across systems and scales, while resilience depends on preparedness, capacity and governance.", ["systemic risk", "resilience", "geopolitical risk", "uncertainty"], "synthesize sources to prioritize resilience", "resilience means returning to the previous condition", P.geography),
  ],
  "global-politics": [
    n("GP1", "Power", "both", "Core concepts > power > hard, soft, structural and relational", "Power is the ability to shape outcomes, agendas, preferences and structures.", ["hard power", "soft power", "structural power", "agency"], "identify and compare forms of power in sources", "power is possessed only by states", P["global-politics"]),
    n("GP2", "Sovereignty", "both", "Core concepts > sovereignty > internal and external", "Sovereignty is authority within territory and independence externally, but it is constrained and contested.", ["sovereignty", "authority", "intervention", "interdependence"], "evaluate a sovereignty claim using sources", "sovereignty is absolute in practice", P["global-politics"]),
    n("GP3", "Legitimacy", "both", "Core concepts > legitimacy > input, output and legal legitimacy", "Legitimacy concerns justified or accepted authority and may come from procedure, performance or norms.", ["legitimacy", "authority", "consent", "accountability"], "compare competing legitimacy claims", "legal authority is automatically legitimate", P["global-politics"]),
    n("GP4", "Interdependence", "both", "Core concepts > interdependence > asymmetry and vulnerability", "Interdependence creates mutual connections but costs and leverage are often unequal.", ["interdependence", "dependency", "vulnerability", "cooperation"], "analyse asymmetric interdependence", "interdependence distributes benefits equally", P["global-politics"]),
    n("GP5", "Political actors", "both", "Actors > states, IGOs, NGOs, MNCs and movements", "Political outcomes arise from interaction among actors with different authority, resources and accountability.", ["state", "IGO", "NGO", "MNC"], "compare actor influence using a case", "only states have political power", P["global-politics"]),
    n("GP6", "Political theories", "both", "Perspectives > realism, liberalism and critical theories", "Theories foreground different actors, interests, institutions and power relations.", ["realism", "liberalism", "critical theory", "perspective"], "interpret the same case through two theories", "a theory is proved by one example", P["global-politics"]),
    n("GP7", "Peace and conflict", "both", "Thematic study > peace and conflict > causes and responses", "Conflict reflects interacting structural, political and identity factors; peace extends beyond absence of violence.", ["negative peace", "positive peace", "conflict", "peacebuilding"], "evaluate conflict management and peacebuilding", "a ceasefire creates positive peace", P["global-politics"]),
    n("GP8", "Development and sustainability", "both", "Thematic study > development and sustainability", "Development models embody contested priorities, indicators and power relations.", ["development", "sustainability", "SDGs", "inequality"], "compare development policies and affected stakeholders", "economic growth is identical to development", P["global-politics"]),
    n("GP9", "Rights and justice", "both", "Thematic study > rights and justice > law and institutions", "Rights claims and justice principles are interpreted and enforced through contested institutions.", ["human rights", "justice", "international law", "accountability"], "evaluate enforcement using a contemporary case", "ratifying a treaty guarantees compliance", P["global-politics"]),
    n("GP-HL1", "Borders and identity", "HL", "HL challenges > borders and identity", "Borders and identities are produced politically and affect mobility, belonging and security.", ["border", "identity", "migration", "security"], "synthesize cases and recommend policy", "borders are only physical lines", P["global-politics"]),
    n("GP-HL2", "Technology and security", "HL", "HL challenges > technology and security", "Technology redistributes surveillance, information and security capabilities while creating governance gaps.", ["technology", "surveillance", "security", "governance"], "recommend an intervention with feasibility limits", "technology is politically neutral", P["global-politics"]),
  ],
  history: [
    n("HIST-A", "Conditions for emergence", "both", "Authoritarian rule > emergence > economic, social and political conditions", "Authoritarian movements emerge through interacting crises, institutions, war, elites and leadership.", ["causation", "crisis", "institution", "leadership"], "compare the importance of conditions in two states", "one crisis alone causes authoritarian rule", P.history, ["Hitler", "Castro", "Mao", "Saddam Hussein"]),
    n("HIST-B", "Establishment of rule", "both", "Authoritarian rule > establishment > persuasion, coercion and legal methods", "Leaders establish rule through varying combinations of legality, force, ideology, alliances and mass support.", ["legal method", "coercion", "ideology", "support"], "compare methods in two cases", "authoritarian leaders always seize power through a coup", P.history, ["Hitler", "Castro", "Napoleon III", "Stalin"]),
    n("HIST-C", "Maintenance of power", "both", "Authoritarian rule > maintenance > repression, propaganda, institutions and cults", "Maintenance combines coercion, consent, institutional control, propaganda and policy performance.", ["repression", "propaganda", "personality cult", "party control"], "evaluate the most effective method across two states", "terror alone explains political durability", P.history, ["Stalin", "Mao", "Hitler", "Saddam Hussein"]),
    n("HIST-D", "Aims and impact of policies", "both", "Authoritarian rule > policies > economic, social, cultural and foreign policy", "Policies pursue ideological and strategic aims but produce uneven outcomes across groups and time.", ["economic policy", "social policy", "foreign policy", "impact"], "compare policy aims and results", "stated aims reliably predict outcomes", P.history, ["Mao", "Castro", "Stalin", "Hitler"]),
    n("HIST-E", "Opposition and challenges", "both", "Authoritarian rule > opposition > forms, strength and response", "Opposition varies by actor, organization and opportunity, while regimes combine concessions and repression.", ["opposition", "resistance", "repression", "concession"], "assess why opposition succeeded or failed", "absence of open protest proves support", P.history),
    n("HIST-F", "End or transformation", "both", "Authoritarian rule > end > collapse, succession and transition", "Authoritarian rule may end through defeat, elite change, protest, negotiated transition or institutional adaptation.", ["transition", "succession", "collapse", "continuity"], "compare reasons for durability or transformation", "a leader's death necessarily ends the regime", P.history),
  ],
  philosophy: [
    n("PHIL1", "Philosophical method", "both", "Being Human > method > argument, objection and counterexample", "Philosophy clarifies concepts and evaluates arguments through reasons, assumptions, objections and replies.", ["argument", "premise", "conclusion", "counterexample"], "reconstruct and assess an argument", "a personal opinion is an argument", P.philosophy),
    n("PHIL2", "Human nature", "both", "Being Human > human nature > rationality, formation and essentialism", "Accounts of human nature dispute whether humans have fixed essences or are formed by biology, culture and choice.", ["rationality", "essentialism", "blank slate", "formation"], "compare essentialist and anti-essentialist positions", "one common trait defines every human", P.philosophy),
    n("PHIL3", "Personhood", "both", "Being Human > personhood > rationality, sentience and agency", "Criteria for personhood affect moral status but face difficult borderline cases.", ["personhood", "sentience", "rationality", "moral agency"], "test criteria using animals, infants or AI", "human DNA is the only possible basis of personhood", P.philosophy),
    n("PHIL4", "Mind and body", "both", "Being Human > mind and body > dualism, physicalism and functionalism", "Theories disagree whether mind is distinct substance, physical process or functional organization.", ["dualism", "physicalism", "functionalism", "consciousness"], "apply theories to an artificial mind", "brain activity alone settles every question about consciousness", P.philosophy),
    n("PHIL5", "The self", "both", "Being Human > self > substance, memory, bundle and no-self", "The self may be understood as substance, psychological continuity, bundle, relational process or illusion.", ["psychological continuity", "bundle theory", "no-self", "relational self"], "evaluate a memory-loss or teleportation case", "memory continuity is complete and error-free", P.philosophy),
    n("PHIL6", "Freedom and responsibility", "both", "Being Human > freedom > determinism, libertarianism and compatibilism", "Freedom may require alternative possibilities, appropriate causes or authentic responsibility under constraints.", ["determinism", "libertarianism", "compatibilism", "responsibility"], "analyse coercion and social conditioning", "causal influence removes all responsibility", P.philosophy),
    n("PHIL7", "Identity over time", "both", "Being Human > identity > body, psychology, narrative and culture", "Personal identity may persist through bodily, psychological, narrative or social continuity.", ["bodily continuity", "narrative identity", "social identity", "persistence"], "evaluate a cloning or dementia thought experiment", "identity requires remaining completely unchanged", P.philosophy),
    n("PHIL8", "Self and other", "HL", "Being Human > self and other > recognition and intersubjectivity", "Recognition by others and relationships may partly constitute agency and identity.", ["recognition", "intersubjectivity", "authenticity", "relationality"], "compare individualist and relational traditions", "the self exists independently of every relationship", P.philosophy),
  ],
  psychology: [
    n("PSY1", "Bias", "both", "Concept lenses > bias > sampling, researcher and cultural bias", "Bias is systematic distortion in design, measurement, interpretation or application.", ["bias", "sampling", "researcher", "culture"], "identify a source of bias and its effect", "bias means any result the researcher dislikes", P.psychology),
    n("PSY2", "Causality", "both", "Concept lenses > causality > inference and alternative explanations", "Causal inference requires temporal order, covariation and control of alternatives.", ["causality", "correlation", "confound", "experiment"], "evaluate a causal claim", "correlation proves causation", P.psychology),
    n("PSY3", "Measurement", "both", "Concept lenses > measurement > operationalization, reliability and validity", "Psychological constructs require operational definitions whose reliability and validity must be evaluated.", ["operationalization", "reliability", "validity", "construct"], "critique how a construct is measured", "a reliable measure must be valid", P.psychology),
    n("PSY4", "Research ethics", "both", "Research methods > ethics > consent, harm, deception and withdrawal", "Ethical decisions balance participant protection, scientific value and context.", ["informed consent", "deception", "protection from harm", "withdrawal"], "redesign a study ethically", "debriefing automatically justifies deception", P.psychology),
    n("PSY5", "Experiments and correlation", "both", "Research methods > quantitative > experiments and correlations", "Experiments manipulate an IV and control alternatives; correlations measure association without manipulation.", ["independent variable", "dependent variable", "correlation", "control"], "compare methods for a research question", "a laboratory setting guarantees validity", P.psychology),
    n("PSY6", "Qualitative research", "both", "Research methods > qualitative > interviews, observations and analysis", "Qualitative research explores meaning and context through reflexive collection and interpretation.", ["interview", "observation", "reflexivity", "thematic analysis"], "evaluate a qualitative design", "qualitative research has no systematic method", P.psychology),
    n("PSY7", "Learning", "both", "Learning and cognition > conditioning and social learning", "Behavior changes through associations, consequences, observation and cognitive mediation.", ["classical conditioning", "operant conditioning", "reinforcement", "social learning"], "apply learning theory to an unfamiliar context", "negative reinforcement is punishment", P.psychology),
    n("PSY8", "Cognition and schemas", "both", "Learning and cognition > schemas, models and biases", "Schemas organize knowledge and influence encoding, retrieval and interpretation.", ["schema", "memory", "cognitive bias", "dual processing"], "explain a behavior using a cognitive model", "schemas are always accurate copies of experience", P.psychology),
    n("PSY9", "Human development", "both", "Human development > biological, cognitive and sociocultural change", "Development reflects interacting biological maturation, experience and cultural participation.", ["development", "sociocultural", "peer influence", "theory of mind"], "compare stage and continuous explanations", "development follows one universal path", P.psychology),
    n("PSY10", "Attachment", "both", "Human development > attachment > formation, variation and outcomes", "Attachment theories explain bonds and outcomes but require cultural and methodological qualification.", ["attachment", "caregiver", "culture", "development"], "evaluate an attachment claim", "one early relationship permanently determines adulthood", P.psychology),
    n("PSY11", "Health and well-being", "both", "Health and well-being > explanations, prevalence and treatment", "Mental health explanations and treatments operate at biological, cognitive, sociocultural and environmental levels.", ["mental health", "prevalence", "treatment", "culture"], "evaluate treatment using effectiveness and responsibility", "one diagnosis has the same meaning in every culture", P.psychology),
    n("PSY12", "Human relationships", "both", "Human relationships > identity, conformity, communication and culture", "Relationships and group behavior reflect identity, norms, cognition, biology and communication.", ["social identity", "conformity", "acculturation", "communication"], "apply theory to a group scenario", "group influence always produces conformity", P.psychology),
    n("PSY-HL1", "Motivation", "HL", "HL lenses > motivation > behavior and context", "Motivation integrates biological, cognitive and sociocultural processes.", ["motivation", "goal", "reward", "context"], "synthesize research sources", "motivation is a stable personal trait", P.psychology),
    n("PSY-HL2", "Culture", "HL", "HL lenses > culture > behavior and research", "Culture shapes meaning and behavior while varying within groups and over time.", ["culture", "enculturation", "norm", "measurement"], "evaluate a cross-cultural claim", "nationality is a direct measure of culture", P.psychology),
    n("PSY-HL3", "Technology", "HL", "HL lenses > technology > cognition, health and relationships", "Technology interacts with users, institutions and contexts rather than producing uniform effects.", ["technology", "change", "measurement", "responsibility"], "use multiple sources to assess a claim", "technology automatically causes social change", P.psychology),
  ],
  anthropology: [
    n("ANT1", "Culture and society", "both", "Foundations > culture, society and holism", "Culture is learned, shared and contested meaning embedded in social organization.", ["culture", "society", "holism", "social organization"], "interpret behavior without fixed cultural stereotypes", "culture is fixed national behavior", P.anthropology),
    n("ANT2", "Emic and etic", "both", "Foundations > emic and etic perspectives", "Emic accounts foreground participant meanings while etic analysis uses comparative analytical categories.", ["emic", "etic", "perspective", "interpretation"], "distinguish participant and analyst explanations", "emic evidence is automatically unbiased", P.anthropology),
    n("ANT3", "Ethnography and participant observation", "both", "Foundations > ethnography > participant observation", "Ethnography builds contextual knowledge through sustained engagement, observation and interpretation.", ["ethnography", "participant observation", "fieldwork", "context"], "evaluate a field method", "one observation represents an entire culture", P.anthropology),
    n("ANT4", "Reflexivity", "both", "Foundations > reflexivity > positionality and representation", "Reflexivity examines how researcher position and relationships shape access, data and representation.", ["reflexivity", "positionality", "representation", "power"], "explain how an observer shapes data", "reflexivity only means admitting bias", P.anthropology),
    n("ANT5", "Identity and socialization", "both", "Concepts > identity, socialization and enculturation", "Identity is produced through relationships, institutions, symbols and change.", ["identity", "socialization", "enculturation", "agency"], "compare identity formation ethnographically", "identity is a fixed individual property", P.anthropology),
    n("ANT6", "Power and inequality", "both", "Concepts > power, inequality and marginality", "Power operates institutionally, economically, symbolically and interpersonally to produce unequal possibilities.", ["power", "inequality", "marginality", "institution"], "analyse two forms of power in an extract", "power is held only by formal leaders", P.anthropology, ["Bourgois", "Chavez"]),
    n("ANT7", "Agency and structure", "both", "Concepts > agency and structure", "People act creatively within constraints that they may reproduce or transform.", ["agency", "structure", "constraint", "change"], "evaluate agency under structural inequality", "structure removes all agency", P.anthropology),
    n("ANT8", "Exchange and reciprocity", "both", "Concepts > exchange, reciprocity and obligation", "Exchange creates material flows and social obligations beyond market price.", ["exchange", "reciprocity", "obligation", "economic organization"], "interpret a non-monetary exchange", "reciprocity requires immediate equal repayment", P.anthropology),
    n("ANT9", "Kinship and relatedness", "both", "Concepts > kinship and relatedness", "Kinship is culturally organized through biological, social, legal and chosen relations.", ["kinship", "relatedness", "household", "social reproduction"], "explain limits of biological definitions", "kinship is universally based only on genetics", P.anthropology),
    n("ANT10", "Ritual and symbolism", "both", "Concepts > ritual, symbolism and belief", "Ritual and symbols express shared meanings while organizing hierarchy, identity and change.", ["ritual", "symbolism", "belief", "authority"], "analyse identity and authority in ritual", "ritual has the same meaning for every participant", P.anthropology),
    n("ANT11", "Globalization and migration", "both", "Concepts > globalization, migration and change", "Global flows are localized through unequal power, hybridity, resistance and institutional boundaries.", ["globalization", "migration", "hybridity", "boundary"], "compare migration and cultural change ethnographically", "globalization makes cultures identical", P.anthropology, ["Kraybill", "Chavez"]),
    n("ANT12", "Ethnographic ethics", "both", "Methods > ethics > consent, vulnerability and representation", "Ethnographic ethics are relational and continue through access, fieldwork, writing and dissemination.", ["consent", "vulnerability", "privacy", "representation"], "evaluate covert observation", "permission from one gatekeeper resolves every ethical issue", P.anthropology),
  ],
  "digital-society": [
    n("DS1", "Data and data analysis", "both", "Content 2.1 > data > collection, processing and representation", "Data systems collect, process and represent selected aspects of people and the world.", ["data", "metadata", "data analysis", "representation"], "trace inputs, processing and outputs", "data are neutral facts without selection", P["digital-society"]),
    n("DS2", "Algorithms and code", "both", "Content 2.2 > algorithms and code > rules, ranking and outcomes", "Algorithms formalize rules and optimize proxies chosen by people and institutions.", ["algorithm", "code", "proxy", "feedback"], "analyse an unintended algorithmic outcome", "algorithms are neutral because computers execute them", P["digital-society"]),
    n("DS3", "Computing devices", "both", "Content 2.3 > computing devices > embedded and connected systems", "Computing devices sense, process, store and communicate data within wider systems.", ["sensor", "device", "processing", "interdependence"], "explain system vulnerability", "a device can be evaluated apart from its users and network", P["digital-society"]),
    n("DS4", "Networks and the internet", "both", "Content 2.4 > networks > infrastructure, access and security", "Networks connect actors and resources while distributing control, risk and access unevenly.", ["network", "internet", "infrastructure", "digital divide"], "evaluate an access intervention", "free websites alone eliminate the digital divide", P["digital-society"]),
    n("DS5", "Media", "both", "Content 2.5 > media > platforms, expression and knowledge", "Digital media shape visibility and expression through platform design, moderation and user practices.", ["media", "platform", "expression", "moderation"], "compare claims and evidence across sources", "higher engagement proves information quality", P["digital-society"]),
    n("DS6", "Artificial intelligence", "both", "Content 2.6 > AI > training, prediction and bias", "AI systems learn patterns from data and embed choices about objectives, labels and acceptable error.", ["AI", "training data", "bias", "accuracy"], "evaluate fairness beyond aggregate accuracy", "high accuracy proves fairness", P["digital-society"]),
    n("DS7", "Robots and autonomy", "both", "Content 2.7 > robots > autonomy, responsibility and values", "Autonomous technologies connect sensors, models and actions while redistributing responsibility.", ["robot", "autonomy", "responsibility", "accountability"], "analyse a reward or decision rule", "autonomous means free from human choices", P["digital-society"]),
    n("DS8", "Power and identity", "both", "Concept lenses > power and identity", "Digital systems classify, incentivize and represent users, affecting identity and institutional power.", ["power", "identity", "classification", "surveillance"], "analyse stakeholder-specific effects", "all users experience a platform in the same way", P["digital-society"]),
    n("DS9", "Values and ethics", "both", "Concept lenses > values and ethics > responsibility and trade-offs", "Technical designs embody values and require ethical evaluation across affected stakeholders.", ["values", "ethics", "responsibility", "stakeholder"], "evaluate a sociotechnical decision", "privacy only means keeping data secret", P["digital-society"]),
    n("DS10", "Systems and change", "both", "Concept lenses > systems and change > feedback and unintended effects", "Digital change emerges through feedback among technology, people, institutions and context.", ["system", "change", "feedback", "unintended consequence"], "construct a system map and explain causality", "innovation automatically causes social change", P["digital-society"]),
    n("DS-HL1", "HL challenges", "HL", "HL extension > challenge families > inequality, governance and sustainability", "HL challenges require cross-context analysis of complex sociotechnical problems.", ["challenge", "inequality", "governance", "uncertainty"], "synthesize multiple sources", "one stakeholder's benefit proves overall success", P["digital-society"]),
    n("DS-HL2", "Interventions", "HL", "HL extension > interventions > feasibility, equity and acceptability", "Interventions must address mechanisms and be evaluated for feasibility, equity, cost, ethics and unintended effects.", ["intervention", "feasibility", "equity", "acceptability"], "recommend and evaluate an intervention", "a single technical fix resolves a social problem", P["digital-society"]),
  ],
  "world-religions": [
    n("WR1", "The human condition", "both", "Introductory unit > human condition > religious responses", "Religions diagnose the human condition and propose paths, practices or relationships that address it.", ["human condition", "belief", "salvation", "liberation"], "compare two religious responses", "all religions define the human problem in the same way", "WR_current_comparative"),
    n("WR2", "Sacred texts and authority", "both", "Introductory unit > authority > texts, traditions and interpretation", "Religious authority may be grounded in texts, traditions, institutions, experience and interpretation.", ["authority", "sacred text", "tradition", "interpretation"], "analyse variation within a tradition", "one text produces one uncontested interpretation", "WR_current_comparative"),
    n("WR3", "Belief and doctrine", "both", "In-depth study > beliefs > doctrine and worldview", "Doctrines organize claims about reality, human purpose and moral life but are interpreted diversely.", ["doctrine", "worldview", "belief", "diversity"], "compare doctrines under a common question", "all adherents hold identical beliefs", "WR_current_comparative"),
    n("WR4", "Ritual and worship", "both", "In-depth study > ritual > worship, community and experience", "Ritual connects embodied practice, belief, community identity and authority.", ["ritual", "worship", "community", "experience"], "evaluate the significance of a ritual", "ritual has the same meaning for every participant", "WR_current_comparative"),
    n("WR5", "Ethics and contemporary issues", "both", "In-depth study > ethics > contemporary religious responses", "Religious ethical responses draw on sources, reasoning, community and context and may differ within traditions.", ["ethics", "contemporary issue", "reasoning", "perspective"], "compare responses to a contemporary issue", "a religion has one automatic policy position", "WR_current_comparative"),
    n("WR6", "Religious experience and change", "both", "In-depth study > experience > identity, conversion and change", "Religious experience is interpreted through personal, communal and cultural frameworks.", ["religious experience", "identity", "conversion", "change"], "analyse personal and institutional interpretations", "private experience requires no interpretation", "WR_current_comparative"),
  ],
};

const contexts = [
  ["Northbridge", "a coastal city", "2026"], ["Mira Valley", "a fast-growing inland region", "2027"], ["Port Aster", "a multilingual trading hub", "2028"],
  ["Lake Orin", "a rural province", "2026"], ["Solmere", "a middle-income state", "2029"], ["East Verdan", "a densely populated district", "2027"],
] as const;
const orgs = ["LoopWorks", "Aster Foods", "Nexa Transit", "BrightHarbor", "Koru Health", "Mosaic Learning"];
const difficultyName = (d: number): Question["difficulty"] => d <= 2 ? "Foundation" : d === 3 ? "Standard" : "Challenge";
const metadata = (node: Node, commandTerm: string, marks: number, d: number, section: string, markschemePoints: string[], commonErrors: string[]) => ({
  commandTerm, syllabusPath: node.path, syllabusProfile: node.profile, difficultyLevel: d as 1 | 2 | 3 | 4 | 5,
  estimatedMinutes: Math.max(2, Math.round(marks * (d >= 4 ? 1.7 : 1.2))), section, markschemePoints, commonErrors,
});

function baseQuestion(subject: Subject, paper: Paper, node: Node, variant: number, d: number, prompt: string, context: string, command: string, marks: number, points: string[], errors: string[], responseType: Question["responseType"] = marks >= 8 ? "extended" : "short"): Question {
  return {
    id: `ins-${subject.id}-${paper.id}-${node.code}-${d}-${variant}`,
    topicCode: node.code, topicTitle: node.title, prompt, context, responseType,
    modelAnswer: points.join(" "), keywords: node.concepts, marks, skill: `${command}: ${node.application}`,
    difficulty: difficultyName(d), premiumOnly: d >= 4, format: "paper", variant,
    ...metadata(node, command, marks, d, paper.name, points, errors),
  };
}

function business(subject: Subject, paper: Paper, node: Node, v: number, d: number): Question {
  const [place] = contexts[v % contexts.length]; const org = orgs[v % orgs.length]; const workers = 38 + v * 7; const growth = 12 + v * 3;
  const ctx = `${org} is a privately held ${place} producer employing ${workers} people. Sales grew ${growth}% last year, but customer returns rose from ${2 + v % 3}% to ${6 + v % 4}%. Managers are considering a $${180 + v * 15},000 investment financed partly by a floating-rate loan. Employees fear work intensification; owners prioritize growth; the local council offers a sustainability grant. Two credible options remain and neither is clearly superior.`;
  if (paper.id === "p2" && (/BM3|BM5.5/.test(node.code))) {
    const price = 70 + v * 2, vc = 38 + v, fixed = 120000 + v * 5000;
    const points = [`Formula: break-even output = fixed costs / contribution per unit.`, `Substitute $${fixed} / ($${price} − $${vc}).`, `Interpret the result against capacity and case risk.`, `A later recommendation must also use stakeholder and uncertainty evidence.`];
    return {
      ...baseQuestion(subject, paper, node, v, d, `${d <= 2 ? "Calculate" : d === 3 ? "Analyse" : "Evaluate"} the financial implications of the proposed investment for ${org}.`, ctx, d <= 2 ? "Calculate" : d === 3 ? "Analyse" : "Evaluate", d <= 2 ? 4 : d === 3 ? 6 : 10, points, ["number without method", "no units", "calculation not interpreted", "recommendation ignores qualitative evidence"]),
      visual: "data-table",
      visualData: {
        title: "Quantitative stimulus",
        columns: ["Price per unit", "Variable cost per unit", "Annual fixed costs", "Planned capacity"],
        rows: [{ label: org, values: [`$${price}`, `$${vc}`, `$${fixed.toLocaleString("en-US")}`, `${5000 + v * 150} units`] }],
      },
    };
  }
  const command = d === 1 ? "Define" : d === 2 ? "Explain" : d === 3 ? "Analyse" : d === 4 ? "Evaluate" : "Recommend";
  const marks = d === 1 ? 2 : d === 2 ? 4 : d === 3 ? 6 : 10;
  const prompt = d === 1 ? `Define the term ${node.concepts[0]}.` : d === 2 ? `Explain one way in which a concept from ${node.title} may affect ${org}.` : d === 3 ? `Analyse how two concepts from ${node.title} apply to ${org}'s decision.` : d === 4 ? `Evaluate the significance of ${node.title} for ${org}'s proposed investment.` : `Recommend whether ${org} should proceed with the investment. Use relevant business tools and justify a coherent action plan.`;
  const points = d === 1 ? [node.definition, `Award the second mark for a distinguishing feature, not an example alone.`] : d === 2 ? [node.definition, `Use one exact fact from ${org}.`, `Show cause → business effect → outcome.`] : d === 3 ? [`Develop two applied chains using different case facts.`, `Explain interrelationships or consequences rather than listing.`, `Credit a relevant limitation.`] : [`Integrate at least three case facts and relevant ${node.concepts.join(", ")}.`, `Develop competing stakeholder or strategic arguments.`, `Recognize assumptions, finance and external uncertainty.`, `${command === "Recommend" ? "Make one feasible choice with sequence and constraints." : "Reach a justified conditional judgement."}`];
  return baseQuestion(subject, paper, node, v, d, prompt, ctx, command, marks, points, ["case name used without application", "tool inserted decoratively", "one-sided judgement", "generic recommendation"]);
}

function economics(subject: Subject, paper: Paper, node: Node, v: number, d: number): Question {
  const [place, setting, year] = contexts[v % contexts.length]; const change = 4 + v % 6;
  const ctx = node.code === "ECO1.1" ? `Original extract (${year}): ${place} has a fixed $${80 + v * 5} million capital budget. Funding a flood-resilient hospital would require postponing a rail link expected to reduce commuting time. Both projects use the same construction workers and imported machinery; lower-income districts disagree over which benefit is more urgent.`
    : node.code === "ECO1.2" ? `Original extract (${year}): ${place} can currently produce at most ${40 + v} units of medical equipment or ${90 + v * 2} units of construction material. Storm damage leaves some labor unemployed. A new training program could raise productivity next year but requires resources now.`
    : node.code.startsWith("ECO2") ? `Original market extract (${year}): In ${place}, demand for a product rose after household incomes increased. Domestic supply is price-inelastic in the short run. The government is considering an intervention linked to ${node.title}; consumer groups and small producers predict unequal effects.`
    : node.code.startsWith("ECO3") || node.code === "ECO-HL" ? `Original macroeconomic extract (${year}): ${place}, ${setting}, recorded ${change}% inflation, a negative output gap and weaker household spending. The government and central bank disagree about the most suitable policy mix. The evidence covers one year and external conditions may change.`
    : `Original global-economy extract (${year}): ${place} depends on two export industries and imports most energy. Its currency changed by ${change}% while a trading partner introduced new protection. Exporters, consumers and lower-income households report different effects.`;
  if (paper.id === "p1") {
    const evalQ = d >= 4; const marks = evalQ ? 15 : 10; const command = evalQ ? "Evaluate" : "Explain";
    const prompt = evalQ ? `Using real-world examples, evaluate the view that policy based on ${node.title} will improve economic well-being.` : `Using a fully labelled diagram, explain the economic mechanism associated with ${node.title} and apply it to the policy choice.`;
    const points = evalQ ? [`Frame ${node.title} with accurate theory and a relevant diagram.`, `Use specific real-world evidence, not a named country alone.`, `Evaluate stakeholders, time, magnitude, assumptions and an alternative.`, `Reach a conditional judgement answering the exact claim.`] : [`Define relevant terms.`, `Draw correct axes, curves, initial equilibrium and required shift/wedge.`, `Explain the mechanism step by step using diagram labels.`, `Develop implications without forcing full evaluation.`];
    return baseQuestion(subject, paper, node, v, d, prompt, ctx, command, marks, points, ["diagram without written explanation", "generic example", "evaluation added only in conclusion", "confuses movement and shift"], "diagram");
  }
  const command = d === 1 ? "Define" : d === 2 ? "Calculate" : d === 3 ? "Explain" : d === 4 ? "Evaluate" : "Recommend";
  const marks = d === 1 ? 2 : d === 2 ? 4 : d === 3 ? 8 : 15;
  const finalIndex = 130 + v; const householdIncome = 2400 + v * 90; const importedCost = 420 + v * 15;
  const prompt = d === 1 ? `Define ${node.concepts[0]}.` : d === 2 ? `Using the data, calculate the percentage change in the index. Show formula, substitution and result.` : d === 3 ? `Using the extract and a labelled diagram, explain two consequences of ${node.title}.` : d === 4 ? `Using the extract and your economic knowledge, evaluate one policy response to ${node.title}.` : `Recommend the most appropriate policy response for ${place}, considering an alternative.`;
  return {
    ...baseQuestion(subject, paper, node, v, d, prompt, ctx, command, marks, [`Use all necessary extract/data evidence.`, `Apply accurate theory and a correctly specified diagram where relevant.`, `Separate short-run from long-run and identify stakeholders.`, `For evaluation, support a conditional judgement and policy limitation.`], ["hidden data assumed", "missing formula or units", "source paraphrase", "unsupported policy assertion"], d === 3 ? "diagram" : undefined),
    visual: "data-table",
    visualData: {
      title: `Economic indicators for ${place}`,
      columns: ["Initial index", "Final index", "Household income", "Imported basket cost"],
      rows: [{ label: String(year), values: [125, finalIndex, `$${householdIncome.toLocaleString("en-US")}`, `$${importedCost.toLocaleString("en-US")}`] }],
      note: "All monetary values are fictional and shown in local currency units.",
    },
  };
}

function geography(subject: Subject, paper: Paper, node: Node, v: number, d: number): Question {
  const [place,, year] = contexts[v % contexts.length]; const a = 42 + v * 3, b = 58 + v * 2;
  const ctx = `Figure 1 shows an original spatial dataset for ${place}, ${year}. Source coverage excludes informal settlements.`;
  const command = d === 1 ? "Describe" : d === 2 ? "Explain" : d === 3 ? "Compare" : d === 4 ? "Evaluate" : "To what extent";
  const marks = paper.id === "p3" ? (d >= 4 ? 16 : 12) : d === 1 ? 2 : d === 2 ? 4 : d === 3 ? 6 : 10;
  const prompt = d === 1 ? `Describe the spatial pattern shown in Figure 1.` : d === 2 ? `Explain one process that may account for the pattern in Figure 1.` : d === 3 ? `Compare the pattern in the urban core and rural periphery, using paired evidence.` : d === 4 ? `Evaluate one strategy for addressing ${node.title} in ${place}.` : `To what extent is power more important than physical process in explaining ${node.title}?`;
  return {
    ...baseQuestion(subject, paper, node, v, d, prompt, ctx, command, marks, [`Use precise values, directions, locations or anomalies from the stimulus.`, `For explanation, connect process → spatial outcome.`, `Use PPPPSS concepts and a relevant case study at the required scale.`, `For high marks, evaluate limitations and reach a qualified judgement.`], ["lists values without pattern", "explains when asked to describe", "case name without detail", "comparison written as separate descriptions"]),
    visual: "geo-map",
    visualData: {
      title: `Spatial distribution of indicator X in ${place}`,
      columns: ["Earlier value", "Current value"],
      rows: [{ label: "Regional mean", values: [a, b] }, { label: "Urban core", values: [a + 7, b + 18] }, { label: "Rural periphery", values: [a - 12, a - 9] }],
      y: [b + 18, b, a - 9, a - 15],
      note: "Highest values follow the transport corridor; the two hatched districts are hazard-exposed.",
    },
  };
}

function globalPolitics(subject: Subject, paper: Paper, node: Node, v: number, d: number): Question {
  const [place,, year] = contexts[v % contexts.length];
  const ctx = `Source A (${year}, government statement): a regional data-sharing agreement is necessary for security and economic stability.\nSource B (${year}, civil-society briefing): oversight is weak and marginalized groups face disproportionate surveillance.\nSource D (${year}, editorial cartoon): a small state holds a giant key while standing beneath cables owned by foreign companies. All sources are fictional parallel material.`;
  const withChart = (question: Question): Question => ({ ...question, visual: "bar-chart", visualData: { title: "Source C — reported change after the agreement", categories: ["Cross-border incidents", "Data-misuse complaints"], y: [-18, 31], yLabel: "Change / %", note: "Values are changes from the previous reporting period." } });
  if (paper.id === "p2") return withChart(baseQuestion(subject, paper, node, v, d, `Discuss the claim that ${node.title} is shaped more by non-state actors than by states.`, ctx, "Discuss", 15, [`Define and debate the central concepts.`, `Use developed contemporary examples and more than one perspective.`, `Integrate a counterargument and mini-judgements.`, `Reach a consistent, qualified conclusion.`], ["one-sided advocacy", "examples only named", "theory name-dropped", "no judgement"]));
  if (paper.id === "p3") return withChart(baseQuestion(subject, paper, node, v, d, `Using the sources and your case-study knowledge, recommend an intervention addressing ${node.title} in ${place}.`, ctx, "Recommend", d >= 4 ? 14 : 8, [`Synthesize more than one source and case.`, `Identify stakeholders and barriers.`, `Evaluate feasibility, rights, legitimacy and alternative perspectives.`, `Give a prioritized recommendation.`], ["recommendation before analysis", "barriers ignored", "sources summarized separately"]));
  const command = d === 1 ? "Identify" : d === 2 ? "Explain" : d === 3 ? "Compare and contrast" : "Evaluate";
  const marks = d === 1 ? 3 : d === 2 ? 4 : d === 3 ? 8 : 10;
  const prompt = d === 1 ? `Identify three points made in Source A about ${node.title}.` : d === 2 ? `Using Source B, explain the concept of ${node.concepts[0]}.` : d === 3 ? `Compare and contrast the perspectives in Sources A and B.` : `Using the sources and your own knowledge, evaluate the claim that the agreement strengthens legitimate political authority.`;
  return withChart(baseQuestion(subject, paper, node, v, d, prompt, ctx, command, marks, [`Use the specified sources directly rather than transcribing.`, `For comparison, pair similarities and differences under common criteria.`, `For evaluation, synthesize source evidence with own knowledge.`, `Judge the claim with a counterargument.`], ["source paraphrase", "two separate source summaries", "origin called biased without purpose/context", "own knowledge absent"]));
}

function history(subject: Subject, paper: Paper, node: Node, v: number, d: number): Question {
  const cases = node.examples.length ? node.examples : ["Castro", "Mao", "Hitler", "Stalin"]; const c1 = cases[v % cases.length], c2 = cases[(v + 1) % cases.length];
  const ctx = `Source A (fictional historian summary): ${c1}'s consolidation depended on institutions and elite choices as well as coercion.\nSource B (fictional contemporary report): public demonstrations and administrative controls appeared simultaneously; its author had limited access outside the capital.`;
  if (paper.id === "p1") {
    const command = d === 1 ? "Identify" : d === 2 ? "Compare and contrast" : d === 3 ? "Evaluate" : "Examine";
    const marks = d === 1 ? 3 : d === 2 ? 6 : d === 3 ? 9 : 9;
    return {
      ...baseQuestion(subject, paper, node, v, d, d === 1 ? `Identify three claims made in Source A.` : d === 2 ? `Compare and contrast what Sources A and B reveal about ${node.title}.` : `Using the sources and your own knowledge, examine the significance of ${node.concepts[0]} for authoritarian rule under ${c1}.`, ctx, command, marks, [`Use source-specific evidence and historical context.`, `Evaluate origin/purpose only in relation to the question.`, `Distinguish causation, consequence and chronology.`, `Avoid claims not supported by source or permitted knowledge.`], ["content summary instead of source analysis", "generic value/limitation", "anachronism", "single-cause claim"]),
      visual: "data-table",
      visualData: {
        title: "Source C — indexed change during consolidation (Year 1 = 100)",
        columns: ["Party membership", "Arrests", "Industrial output"],
        rows: [0, 1, 2, 3].map((yearOffset) => ({ label: `Year ${yearOffset + 1}`, values: [100 + yearOffset * (6 + v % 3), 100 + yearOffset * (15 - v % 4), 100 + yearOffset * (3 + v % 2)] })),
        note: "The figures are fictional parallel-source data; indices are not absolute totals.",
      },
    };
  }
  const prompt = d <= 2 ? `Evaluate the importance of ${node.concepts[0]} in the ${node.title.toLowerCase()} of one authoritarian state.` : `Compare and contrast the role of ${node.concepts[0]} in ${node.title.toLowerCase()} in ${c1} and ${c2}.`;
  return baseQuestion(subject, paper, node, v, d, prompt, "No prescribed source. Use precise, relevant historical evidence from the cases studied.", d <= 2 ? "Evaluate" : "Compare and contrast", 15, [`Establish a clear thesis responsive to the command term.`, `Use precise evidence with actors, policies, dates/periods and outcomes.`, `Organize comparative paragraphs by common criteria, not two halves.`, `Weigh relative significance and qualify the conclusion.`], ["narrative chronology", "two separate case descriptions", "unsupported historiography", "evidence named but not analysed"]);
}

function philosophy(subject: Subject, paper: Paper, node: Node, v: number, d: number): Question {
  const stimuli = [
    "A hospital can copy a patient's memories into a synthetic body, but the biological patient remains conscious.",
    "An artificial system argues, reports pain and revises its goals, yet its designer says it only imitates understanding.",
    "A person under strong social pressure makes a choice they later describe as entirely their own.",
    "After severe memory loss, a person keeps relationships and habits but rejects their earlier life story.",
  ];
  const ctx = `Stimulus (original thought experiment): ${stimuli[v % stimuli.length]}`;
  const prompt = `Identify the central philosophical issue concerning ${node.title} raised by the stimulus and develop a reasoned response.`;
  return baseQuestion(subject, paper, node, v, d, prompt, ctx, "Discuss", d >= 4 ? 25 : 15, [`Identify a precise issue and connect it explicitly to the stimulus and Being Human.`, `Explain at least two positions by reconstructing their reasoning.`, `Apply positions to the stimulus, then develop objections and replies.`, `Conclude what has and has not been established.`], ["describes stimulus only", "philosopher name-dropping", "assertion without argument", "new argument introduced in conclusion"]);
}

function psychology(subject: Subject, paper: Paper, node: Node, v: number, d: number): Question {
  const sample = 48 + v * 6; const retrievalNow = 76 - v, retrievalLater = 61 - v, rereadNow = 69 - v, rereadLater = 47 - v;
  const ctx = `Supplied study (original): ${sample} students were assigned by existing class to either a guided retrieval activity or rereading. Recall was measured immediately and after seven days. Teachers knew group allocation, participation required parental consent, and prior achievement was not measured.`;
  const withResults = (question: Question): Question => ({ ...question, visual: "bar-chart", visualData: { title: "Mean recall score by condition and time", categories: ["Retrieval — immediate", "Retrieval — 7 days", "Rereading — immediate", "Rereading — 7 days"], y: [retrievalNow, retrievalLater, rereadNow, rereadLater], yLabel: "Mean recall / %", note: `Total sample: ${sample}; intact classes were used rather than individual random allocation.` } });
  if (paper.id === "p3") {
    const marks = d === 1 ? 3 : d <= 3 ? 6 : 15; const command = d === 1 ? "Interpret" : d <= 3 ? "Analyse" : "Discuss";
    const prompt = d === 1 ? `Interpret one pattern in the supplied quantitative results.` : d <= 3 ? `Analyse one methodological feature of the supplied study with reference to ${node.title}.` : `Using the supplied study and at least two additional sources described in the resource booklet, discuss the validity of the claim that retrieval activity causes durable learning improvement.`;
    return withResults(baseQuestion(subject, paper, node, v, d, prompt, `${ctx}\nResource booklet note: Source B is a qualitative interview study with a small self-selected sample; Source C is a two-year observational dataset showing mixed effects by prior achievement.`, command, marks, [`Use exact source evidence.`, `Separate correlation, causation and methodological inference.`, `For 15 marks, integrate at least three sources and background knowledge.`, `Reach a proportionate conclusion about validity.`], ["study detail invented", "correlation treated as cause", "sources listed not synthesized", "generic method limitation"]));
  }
  if (paper.id === "p2") return withResults(baseQuestion(subject, paper, node, v, d, d <= 2 ? `Describe how one research method could be used in a class practical investigating ${node.title}.` : d === 3 ? `Compare and contrast two methods for investigating ${node.title}.` : `Discuss the supplied study with reference to measurement, bias and responsibility.`, ctx, d <= 2 ? "Describe" : d === 3 ? "Compare and contrast" : "Discuss", d <= 2 ? 4 : d === 3 ? 6 : 15, [`Specify aim, sample, operationalization and procedure.`, `Connect strengths/limitations to this research question.`, `Use concepts analytically rather than as headings.`, `For design, align method, data and ethics.`], ["method named without procedure", "reliability and validity confused", "student's own practical invented", "ethics generic"]));
  const marks = d === 1 ? 4 : d <= 3 ? 6 : 15; const command = d === 1 ? "Describe" : d <= 3 ? "Explain" : "Critically analyse";
  const prompt = d === 1 ? `Describe ${node.title} and give one relevant example.` : d <= 3 ? `Explain how ${node.title} is demonstrated in the scenario.` : `Critically analyse one explanation of behavior through the concept of ${node.concepts[0]}.`;
  const question = baseQuestion(subject, paper, node, v, d, prompt, d <= 3 ? ctx : "Use relevant theories and research. Named-study procedural recall is not the primary demand.", command, marks, [`Accurately explain the psychological content.`, `Apply it to the example or unfamiliar scenario.`, `For 15 marks, evaluate research/method, perspectives and the named concept.`, `Reach a focused conclusion.`], ["named study recited without relevance", "scenario not applied", "method evaluation detached", "concept only defined"]);
  return d <= 3 ? withResults(question) : question;
}

function anthropology(subject: Subject, paper: Paper, node: Node, v: number, d: number): Question {
  const extract = `Fictional ethnographic extract: In ${contexts[v % contexts.length][0]}'s night market, vendors share childcare without fixed repayment. A red cloth marks stalls whose owners joined a new delivery app. Older vendors call the cloth a sign of mutual support; younger workers say it helps customers find them online. The visiting researcher is repeatedly offered higher prices after being mistaken for a tourist.`;
  const command = d === 1 ? "Identify" : d === 2 ? "Explain" : d === 3 ? "Analyse" : d === 4 ? "Compare" : "Discuss";
  const marks = d === 1 ? 2 : d === 2 ? 6 : d === 3 ? 8 : d === 4 ? 10 : 15;
  const prompt = d === 1 ? `Identify one anthropological concept illustrated by the extract.` : d === 2 ? `Explain how the extract illustrates ${node.title}.` : d === 3 ? `Analyse two interpretations of ${node.title} in the extract.` : d === 4 ? `Compare ${node.title} in the extract with one studied ethnography.` : `Discuss the claim that ${node.misconception}, using detailed comparative ethnographic evidence.`;
  return baseQuestion(subject, paper, node, v, d, prompt, extract, command, marks, [`Use specific extract or ethnographic detail and its field context.`, `Integrate concepts and participant perspectives.`, `For comparison, pair similarities and differences under common criteria.`, `Where relevant, analyze positionality and representation.`], ["broad cultural generalization", "ethnography named without detail", "emic perspective missing", "inference presented as observation"]);
}

function digitalSociety(subject: Subject, paper: Paper, node: Node, v: number, d: number): Question {
  const [place,, year] = contexts[v % contexts.length];
  const ctx = `Source A (${year}): ${place} deploys an automated public-service ranking system using application history, location, household records and user feedback. Officials report processing time fell ${18 + v * 2}%.\nSource B: an advocacy group finds higher rejection rates in two low-connectivity districts; subgroup accuracy is not published.\nSource C: the vendor states that aggregate accuracy is 94% and that final decisions remain with staff.`;
  const command = d === 1 ? "Define" : d === 2 ? "Outline" : d === 3 ? "Explain" : d === 4 ? "Evaluate" : "Recommend";
  const marks = d === 1 ? 2 : d === 2 ? 4 : d === 3 ? 6 : paper.id === "p3" ? 12 : 8;
  const prompt = d === 1 ? `Define ${node.concepts[0]}.` : d === 2 ? `Outline two system components relevant to ${node.title}.` : d === 3 ? `Explain two ways in which ${node.title} may shape outcomes for stakeholders.` : d === 4 ? `Using the sources, evaluate the claim that the system is fair.` : `Recommend an intervention and evaluate it using equity, feasibility, acceptability, cost and accountability.`;
  return {
    ...baseQuestion(subject, paper, node, v, d, prompt, ctx, command, marks, [`Explain the digital system, not only social impact.`, `Use source claims, evidence, perspectives and limitations.`, `Distinguish stakeholder effects and avoid homogeneous users.`, `For evaluation/recommendation, weigh criteria and reach a qualified judgement.`], ["technology labelled good or bad", "aggregate accuracy equated with fairness", "correlation treated as causation", "intervention has no evaluation criteria"]),
    visual: "process-flow",
    visualData: { title: "System map", nodes: ["Data collection", "Cleaning", "Model score", "Staff review", "Service decision", "Appeal", "Feedback data"], note: "Appeal outcomes feed back into later data collection." },
  };
}

function worldReligions(subject: Subject, paper: Paper, node: Node, v: number, d: number): Question {
  const ctx = `Original comparative stimulus: Community A interprets a long-established practice as a duty that preserves collective identity. A younger member argues that the same underlying belief can be expressed through a new form. Community B addresses a comparable human concern through a different source of authority and ritual structure. Neither community is presented as internally uniform.`;
  const command = d === 1 ? "Define" : d === 2 ? "Outline" : d === 3 ? "Compare" : d === 4 ? "Evaluate" : "Discuss";
  const marks = d === 1 ? 2 : d === 2 ? 4 : d === 3 ? 6 : d === 4 ? 10 : 15;
  const prompt = d === 1 ? `Define ${node.concepts[0]} in the study of world religions.` : d === 2 ? `Outline two ways in which ${node.title.toLowerCase()} is expressed in the stimulus.` : d === 3 ? `Compare how two religious traditions approach ${node.title.toLowerCase()}.` : d === 4 ? `Evaluate the significance of interpretation in shaping ${node.title.toLowerCase()}.` : `Discuss the claim that ${node.misconception}, using detailed evidence from two traditions.`;
  return baseQuestion(subject, paper, node, v, d, prompt, ctx, command, marks, [`Establish accurate features of both traditions.`, `Use direct paired comparison under common criteria.`, `Recognize internal diversity and context.`, `For evaluation, reach a qualified judgement supported by specific practices or sources.`], ["traditions described in separate halves", "internal diversity ignored", "belief generalized from one adherent", "moral judgement replaces analysis"]);
}

const builders: Record<string, (subject: Subject, paper: Paper, node: Node, v: number, d: number) => Question> = { business, economics, geography, "global-politics": globalPolitics, history, philosophy, psychology, anthropology, "digital-society": digitalSociety, "world-religions": worldReligions };

export function getINSTopics(subjectId: string, level: Level): Topic[] | null {
  const nodes = INS_TOPICS[subjectId];
  return nodes ? nodes.filter((node) => level === "HL" || node.level === "both") : null;
}

export function buildINSQuestionPool(subject: Subject, level: Level, paper: Paper, topics: Topic[], premium: boolean, seed: number, excludeIds: string[]): Question[] | null {
  const build = builders[subject.id]; const nodes = INS_TOPICS[subject.id];
  if (!build || !nodes || paper.id === "concept") return null;
  const selected = topics.map((topic) => nodes.find((node) => node.code === topic.code)).filter((node): node is Node => Boolean(node));
  const excluded = new Set(excludeIds); const pool: Question[] = [];
  for (let variant = 0; variant < 12; variant += 1) for (let difficulty = 1; difficulty <= 5; difficulty += 1) {
    if (!premium && difficulty >= 4) continue;
    selected.forEach((node) => pool.push(build(subject, paper, node, variant, difficulty)));
  }
  return pool.filter((question) => !excluded.has(question.id)).sort((a, b) => Math.sin(seed + a.id.length * 17 + (a.variant ?? 0)) - Math.sin(seed + b.id.length * 17 + (b.variant ?? 0)));
}
